|<img src="https://www.udp.cl/cms/wp-content/uploads/2021/06/UDP_LogoRGB_2lineas_Color_SinFondo.png" width="500" height="100">| <p> Ciencias de Datos para la Economía</p>  <p> Ingeniería Comercial </p><p> Profesor: Luis Cuevas Parra </p><p>Unidad I: Introducción a Python</p>|
|--- | :--- |

# **Indice**<a name="id1"></a>

* [1.3. Estructuras de Control de Flujo](#id3)
  * [1.3.1. if, elif y else](#id3.1)
  * [1.3.2. Bucle for](#id3.2)
  * [1.3.3. Bucle while](#id3.3)
  * [1.3.4. range](#id3.4)
  * [1.3.5. Otras funciones para realizar iteraciones](#id3.5)
  <div align="justify">
* [1.4. Manejo de Errores](#id4)
* [1.5. Funciones](#id5)
* [1.6. Funciones Lambda](#id6)

<div align="justify">

# [**1.3. Estructuras de Control de Flujo**](#id1)<a name="id3"></a>

Hemos dado nuestros primeros pasos con Python, donde hemos realizados algunas operaciones que pueden resultar repetitivas. Con la finalidad de economizar código y evitar la maldición del copiar y pegar, podemos dar uso de las estructuras de control de flujo.

Como su nombre lo indica, las estructuras de control nos permiten controlar la manera en que se ejecuta nuestro código. Estas estructuras indican condiciones que se deben cumplir con la finalidad de realizar una operación, o bien que se debe ejecutar.

Este tipo de operaciones nos ayudaran con la manipulación y transformación de datos. A continuación revisaremos las siguientes estructuras de control y la finalidad de uso de cada una de ella


|Estructura de control	| Descripción   |
|-----------------------|-------------  |
|if, elif, else         |Si, sino       |
|for	                  |Para cada valor|
|while	                |Mientras       |
|break	                |Interrupción   |
|continue               |Siguiente      |



<div/>

<div align= 'justify'>

## [**1.3.1. if, elif y else**](#id1)<a name="id3.1"></a>

La sentencia `if` es una de las más utilizadas y conocidas en las estructuras de control de flujo. Si la sentencia indicada es verdadera, el código inicado se ejecuta.

A continuación revisaremos un ejemplo

<div/>

In [ ]:
x = int(input('Ingrese un número '))

Ingrese un número 6

In [ ]:
x = int(input('Ingrese un número '))

# bloque if
if x < 0:
  print(f'el valor {x} es negativo')

Ingrese un número -3
el valor -3 es negativo

<div align= 'justify'>

Note que si ingresamos un valor no negativo, la sentencia no nos arroja resultado alguno, dado que la sentencia `if` solo ejecuta el código en caso que la evaluación del mismo sea `True`.

Si necesitamos agregar una nueva condición, podemos hacer uso de la sentencia `else`.

<div/>

In [ ]:
x = int(input('Ingrese un número '))

# bloque if
if x < 0:
  print(f'el valor {x} es negativo')
# bloque else
else:
  print(f'el valor {x} es positivo')

Ingrese un número 6
el valor 6 es positivo

In [ ]:
x = int(input('Ingrese un número '))

# bloque if
if x < 0:
  print(f'el valor {x} es negativo')
# bloque else
else:
  if x > 0:
    print(f'el valor {x} es negativo')
  # bloque else
  else:
    print(f'el valor {x} es neutro')

Ingrese un número 0
el valor 0 es neutro

In [ ]:
x = int(input('Ingrese un número '))

<div align= 'justify'>

Sin embargo, ¿Qué ocurre si indicamos el número 0?. Sabemos que el cero no es positivo ni negativo, por tanto estaríamos incurriendo en un error en nuestra operación. Por lo tanto tendríamos que agregar un nuevo bloque. Para esto utilizaremos la estructura `elif`, la cual va entre la sentencia `if` y la sentencia `else`.

<div/>

In [ ]:
x = int(input('Ingrese un número '))

# bloque if
if x < 0:
  print(f'el valor {x} es negativo')
elif x > 0:
  print(f'el valor {x} es positivo')
# bloque else
else:
  print(f'el valor {x} es neutro')

Ingrese un número 0
el valor 0 es neutro

<div align="justify">

## [**1.3.2. Bucle for**](#id1)<a name="id3.2"></a>

Este bucle nos ayuda a realizar una iteración sobre un conjunto de valores, tales como las listas o tuplas o un iterador.

La sintaxis básica es la siguiente:

```
for valor in conjunto_de_valores {
  realizar operación el con valor
}
```

A continuación realizaremos una bucle `for` para imprimir número de 1 al 10. Note que indicamos como elemento de término el número 11 en vez del 10 dado que el último valor no lo incluye.
<div/>

In [ ]:
range(1,11)

range(1, 11)

In [ ]:
for numero in range(1,11):
  print(numero)

1
2
3
4
5
6
7
8
9
10

In [ ]:
for numero in range(11):
  print(numero)

0
1
2
3
4
5
6
7
8
9
10

In [ ]:
['jj','Ll','ss'][2].upper()

'SS'

In [ ]:
# Pasar str a mayuscula
for i in ['jj','Ll','ss']:
  print(i.upper())

JJ
LL
SS

In [ ]:
# Pasar str a minúsculas
for i in ['jj','Ll','ss']:
  print(i.lower())

jj
ll
ss

In [ ]:
# Pasar str a título
for i in ['jj','Ll','ss']:
  print(i.title())

Jj
Ll
Ss

```python
## Cambiar nombre columnas usando bucle for
for columna in list(df.columns):
  df.rename(columns={columna: columna.upper()}, inplace = True)
```

<div align= 'justify'>

También, podemos por medio del uso del loop `for` avanzar a la siguiente iteración, saltando el resto del bloque, utilizando la palabra reservada `continue`.

<div/>

In [ ]:
1%2

1

In [ ]:
10%2

0

In [ ]:
for numero in range(1,21):
  if numero % 2 != 0: # modulo o resto de la división. Si el número es impar continuar, si es par imprimir
    continue
  print(f" Este es un número par = {numero}")

 Este es un número par = 2
 Este es un número par = 4
 Este es un número par = 6
 Este es un número par = 8
 Este es un número par = 10
 Este es un número par = 12
 Este es un número par = 14
 Este es un número par = 16
 Este es un número par = 18
 Este es un número par = 20

In [ ]:
for numero in range(1,21):
  if numero % 2 == 0: # modulo o resto de la división. Si el número es impar continuar, si es par imprimir
    print(f" Este es un número par = {numero}")

 Este es un número par = 2
 Este es un número par = 4
 Este es un número par = 6
 Este es un número par = 8
 Este es un número par = 10
 Este es un número par = 12
 Este es un número par = 14
 Este es un número par = 16
 Este es un número par = 18
 Este es un número par = 20

<div align= 'justify'>

Podemos usar el bucle `for` de manera conjunta con sentencias condicionales, tales como `if else`.

<div/>

In [ ]:
# Aplicando if else
for numero in range(1, 21):
    if numero % 2 != 0: # modulo o resto de la división
        print(f"Este es un número impar = {numero}")
    else:
        print(f"Este es un número par   = {numero}")

Este es un número impar = 1
Este es un número par   = 2
Este es un número impar = 3
Este es un número par   = 4
Este es un número impar = 5
Este es un número par   = 6
Este es un número impar = 7
Este es un número par   = 8
Este es un número impar = 9
Este es un número par   = 10
Este es un número impar = 11
Este es un número par   = 12
Este es un número impar = 13
Este es un número par   = 14
Este es un número impar = 15
Este es un número par   = 16
Este es un número impar = 17
Este es un número par   = 18
Este es un número impar = 19
Este es un número par   = 20

In [ ]:
# Usando np.where
import numpy as np

for numero in range(1, 21):
    result = np.where(numero % 2 != 0,
                      f"Este es un número impar = {numero}",
                      f"Este es un número par   = {numero}")
    print(result)

Este es un número impar = 1
Este es un número par   = 2
Este es un número impar = 3
Este es un número par   = 4
Este es un número impar = 5
Este es un número par   = 6
Este es un número impar = 7
Este es un número par   = 8
Este es un número impar = 9
Este es un número par   = 10
Este es un número impar = 11
Este es un número par   = 12
Este es un número impar = 13
Este es un número par   = 14
Este es un número impar = 15
Este es un número par   = 16
Este es un número impar = 17
Este es un número par   = 18
Este es un número impar = 19
Este es un número par   = 20

<div align= 'justify' >

Un bucle `for` puede darse por finalizado por medio del uso de la palabra reservada `break`.

<div/>

In [ ]:
valores = [1,2,3,4,None,7]

for valor in valores:
  if valor == None: # Si el valor de la iteración es None, el bucle terminará
    break
  print(valor)

1
2
3
4

<div align= 'justify' >

### **Lista de Comprensión**

Otra forma de realizar bucles for e por medio de una lista de comprensión, donde básicamente indicamos en primer lugar la acción que queremo ejecutar y luego indicamos nuestro iterador `for`. Recordemos los siguientes ejemplos

```
# Imprimir un número
for numero in range(1,11):
  print(numero)
```
```
# Aplicando if else
for numero in range(1, 21):
    if numero % 2 != 0: # modulo o resto de la división
        print(f"Este es un número impar = {numero}")
    else:
        print(f"Este es un número par   = {numero}")

```
<div/>

<div align= 'justify' >

Para realizar estos bucles por medio de lista de comprensión, en primer lugar indicamos la acción a realizar y posteriormente realizamos el bucle.

Para el primer ejemplo, primero realizamos la impresión y luego el bucle `for`.En tanto, para el segundo ejemplo, en primer ligar mostramos la impresión, luego la condición de cumplimiento y finalmente el bucle `for`.
<div/>

In [ ]:
# Ejemplo 1
[numero for numero in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
# Ejemplo 2
[f'Este es un número impar = {numero}' if numero % 2 != 0 else f'Este es un número par   = {numero}' for numero in range(1, 21)]

['Este es un número impar = 1',
 'Este es un número par   = 2',
 'Este es un número impar = 3',
 'Este es un número par   = 4',
 'Este es un número impar = 5',
 'Este es un número par   = 6',
 'Este es un número impar = 7',
 'Este es un número par   = 8',
 'Este es un número impar = 9',
 'Este es un número par   = 10',
 'Este es un número impar = 11',
 'Este es un número par   = 12',
 'Este es un número impar = 13',
 'Este es un número par   = 14',
 'Este es un número impar = 15',
 'Este es un número par   = 16',
 'Este es un número impar = 17',
 'Este es un número par   = 18',
 'Este es un número impar = 19',
 'Este es un número par   = 20']

<div align= 'justify' >

## [**1.3.3. Bucle while**](#id1)<a name="id3.3"></a>

Este bucle nos ayuda a realizar una iteración sobre un conjunto de valores, tales como las listas o tuplas o un iterador, hasta que se cumpla una condición. El código seguirá ejecutándose hasta que la condición booleana arroje un valor `False`


A continuación realizaremos una bucle `while` para imprimir números de una lista menores que 6.

<div/>

In [ ]:
lista = [1,2,3,4,5,6,7,8,9,10]

for numero in lista:
    while numero < 6:
        print(f'El número {numero} es menor que 6')
        numero += 1 # sumar uno al valor iterado
        break # dar finalizado el bucle cuando la condición se cumpla

El número 1 es menor que 6
El número 2 es menor que 6
El número 3 es menor que 6
El número 4 es menor que 6
El número 5 es menor que 6

In [ ]:
x = 5
while x > 0: # Ejecutar el operador resta hasta que x deje de ser mayor que cero
  x -=1
  print(x)

4
3
2
1
0

<div align= 'justify' >

## [**1.3.4. range**](#id1)<a name="id3.4"></a>

La función `range()` retorna un iterador que producen una secuencia de números enteros espaciados uniformemente

<div/>

In [ ]:
# generar objeto range
range(10)

range(0, 10)

In [ ]:
[numero for numero in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# generar objeto range como una lista
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# generar objeto range como una lista y con espaciado de dos elementos
list(range(0,11,2))

[0, 2, 4, 6, 8, 10]

<div align= 'justify' >

## [**1.3.5. Otras funciones para realizar iteraciones**](#id1)<a name="id3.5"></a>

Hemos visto algunas maneras de realizar iteraciones sobre listas, las cuales pueden ser aplicadas a datos Series o Dataframe. Adicionalmente, revisaremos otros métodos que ofrece la biblioteca de Pandas, dado que cuenta con funciones optimizadas para el manejo de operaciones vectorizadas.

A continuación, revisaremos los métodos más utilizados para esta tarea de iteración.

La iteración en los DataFrames de Pandas se puede llevar a cabo de diferentes maneras, pero es importante tener en cuenta que Pandas está optimizado para operaciones vectorizadas y no siempre es necesario iterar explícitamente sobre los DataFrames.


* **items**
* **iterrows**
* **itertuples**

<div/>

In [ ]:
import pandas as pd

In [ ]:
df_datos = pd.DataFrame({'nombre':['David','Oscar','Elena','Diana','Hernan','Maria','David'],
            'apellido':['Perez','Parra','Berrios','Diaz','Alvarado','Leal','Cornejo'],
            'año_nacimiento':[2000,2001,1982,2003,1998,1999,2001],
            'Pais':['Chile','Brasil','Argentina','Chile','Chile','Brasil','Uruguay'],
            'Monto':[200000, 210000, 190000, 201000, 150000, 198203, None]})

In [ ]:
list(df_datos.columns)

['nombre', 'apellido', 'año_nacimiento', 'Pais', 'Monto']

In [ ]:
df_datos

   nombre  apellido  año_nacimiento       Pais     Monto
0   David     Perez            2000      Chile  200000.0
1   Oscar     Parra            2001     Brasil  210000.0
2   Elena   Berrios            1982  Argentina  190000.0
3   Diana      Diaz            2003      Chile  201000.0
4  Hernan  Alvarado            1998      Chile  150000.0
5   Maria      Leal            1999     Brasil  198203.0
6   David   Cornejo            2001    Uruguay       NaN

In [ ]:
for columna in list(df_datos.columns):
  print(columna.upper())

In [ ]:
#@title Pasar nombres de columnas a mayuscula usando lista de comprensión
df_datos.columns = [columna.upper() for columna in list(df_datos.columns)]

In [ ]:
for columna in list(df_datos.columns):
  df_datos.rename(columns={columna: columna.upper()},  inplace = True)

In [ ]:
df_datos

  NOMBRE_MOD APELLIDO_MOD  AÑO_NACIMIENTO_MOD   PAIS_MOD  MONTO_MOD
0      David        Perez                2000      Chile   200000.0
1      Oscar        Parra                2001     Brasil   210000.0
2      Elena      Berrios                1982  Argentina   190000.0
3      Diana         Diaz                2003      Chile   201000.0
4     Hernan     Alvarado                1998      Chile   150000.0
5      Maria         Leal                1999     Brasil   198203.0
6      David      Cornejo                2001    Uruguay        NaN

In [ ]:
list(df_datos.columns)

['NOMBRE', 'APELLIDO', 'AÑO_NACIMIENTO', 'PAIS', 'MONTO']

In [ ]:
#@title Pasar nombres de columnas a mayuscula usando bucle for
for columna in list(df_datos.columns):
  df_datos.rename(columns={columna: columna.upper()}, inplace = True)

In [ ]:
#df_datos.rename(columns={'NOMBRE': 'nombre'}, inplace = True)

In [ ]:
new_columns = ['name',	'last_name',	'birth_year', 'country','amount']

In [ ]:
old_columns = list(df_datos.columns)
old_columns

['NOMBRE_MOD', 'APELLIDO_MOD', 'AÑO_NACIMIENTO_MOD', 'PAIS_MOD', 'MONTO_MOD']

In [ ]:
for old, new in zip(old_columns, new_columns):
  print(f"{old}: {new}")

NOMBRE_MOD: name
APELLIDO_MOD: last_name
AÑO_NACIMIENTO_MOD: birth_year
PAIS_MOD: country
MONTO_MOD: amount

In [ ]:
for old, new in zip(old_columns, new_columns):
  df_datos.rename(columns={old: new}, inplace = True)

In [ ]:
df_datos

     name last_name  birth_year    country    amount
0   David     Perez        2000      Chile  200000.0
1   Oscar     Parra        2001     Brasil  210000.0
2   Elena   Berrios        1982  Argentina  190000.0
3   Diana      Diaz        2003      Chile  201000.0
4  Hernan  Alvarado        1998      Chile  150000.0
5   Maria      Leal        1999     Brasil  198203.0
6   David   Cornejo        2001    Uruguay       NaN

<div align= 'justify' >

### **items()**

Este método permite iterar cada columna de un DataFrame. Esta iteración retorna lo siguiente:

- Nombre de columnas del DataFrame
- El contenido de cada columnas como un objeto Series de Pandas


<div/>

In [ ]:
for nombre_columna, serie_valores in df_datos.items():
  print('nombre_columna: ', nombre_columna)
  print('serie_valores\n', serie_valores)
  print('Total_valores_unicos\n', serie_valores.nunique())
  print('\n')

nombre_columna:  name
serie_valores
 0     David
1     Oscar
2     Elena
3     Diana
4    Hernan
5     Maria
6     David
Name: name, dtype: object
Total_valores_unicos
 6


nombre_columna:  last_name
serie_valores
 0       Perez
1       Parra
2     Berrios
3        Diaz
4    Alvarado
5        Leal
6     Cornejo
Name: last_name, dtype: object
Total_valores_unicos
 7


nombre_columna:  birth_year
serie_valores
 0    2000
1    2001
2    1982
3    2003
4    1998
5    1999
6    2001
Name: birth_year, dtype: int64
Total_valores_unicos
 6


nombre_columna:  country
serie_valores
 0        Chile
1       Brasil
2    Argentina
3        Chile
4        Chile
5       Brasil
6      Uruguay
Name: country, dtype: object
Total_valores_unicos
 4


nombre_columna:  amount
serie_valores
 0    200000.0
1    210000.0
2    190000.0
3    201000.0
4    150000.0
5    198203.0
6         NaN
Name: amount, dtype: float64
Total_valores_unicos
 6

<div align= 'justify' >

Esta iteración podemos combinarlas con funciones, tales como cantidad de registros únicos, registros únicos, junto con el nombre de las columnas del DataFrame. A continuación realizaremos un ejemplo que nos muestre el nombre de la columna, cantidad de elementos únicos y sus elementos no duplicados.

<div/>

In [ ]:
for nombre_columna, serie_pandas in df_datos.items():
  print(f'Nombre Columna: {nombre_columna}')
  # Cantidad elementos únicos
  print(f'Cantidad de elementos únicos: {serie_pandas.nunique()}')
  # valores ordenados y únicos
  print(f'Elementos únicos: {sorted(serie_pandas.unique())}')
  print(f'Tipo de datp: {serie_pandas.dtype}')
  print('\n')

Nombre Columna: name
Cantidad de elementos únicos: 6
Elementos únicos: ['David', 'Diana', 'Elena', 'Hernan', 'Maria', 'Oscar']
Elementos únicos: object


Nombre Columna: last_name
Cantidad de elementos únicos: 7
Elementos únicos: ['Alvarado', 'Berrios', 'Cornejo', 'Diaz', 'Leal', 'Parra', 'Perez']
Elementos únicos: object


Nombre Columna: birth_year
Cantidad de elementos únicos: 6
Elementos únicos: [np.int64(1982), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2003)]
Elementos únicos: int64


Nombre Columna: country
Cantidad de elementos únicos: 4
Elementos únicos: ['Argentina', 'Brasil', 'Chile', 'Uruguay']
Elementos únicos: object


Nombre Columna: amount
Cantidad de elementos únicos: 6
Elementos únicos: [np.float64(150000.0), np.float64(190000.0), np.float64(198203.0), np.float64(200000.0), np.float64(201000.0), np.float64(210000.0), np.float64(nan)]
Elementos únicos: float64

<div align= 'justify' >

### **iterrows()**

Este método se utiliza para iterar sobre las filas de un DataFrame. Sin embargo, se debe tener en cuenta que `iterrows()` no siempre es la opción más eficiente para iterar sobre un DataFrame grande debido a su naturaleza basada en bucles y puede ser lento en comparación con otras opciones más vectorizadas.

A continuación veremos un ejemplo de uso, donde buscamos realizar una operación algebraica elemento a elemento de una columna específica. Además, crearemos una columnas con el nombre completo de la persona.

<div/>

In [ ]:
df_datos

     name last_name  birth_year    country    amount
0   David     Perez        2000      Chile  200000.0
1   Oscar     Parra        2001     Brasil  210000.0
2   Elena   Berrios        1982  Argentina  190000.0
3   Diana      Diaz        2003      Chile  201000.0
4  Hernan  Alvarado        1998      Chile  150000.0
5   Maria      Leal        1999     Brasil  198203.0
6   David   Cornejo        2001    Uruguay       NaN

In [ ]:
# Agregar columna Bono, multiplicando un porcentaje a la columna Monto
porcentaje = float(0.1)

for indice, fila in df_datos.iterrows():
  # Multiplicar porcentaje a los elementos de la columna Monto
  df_datos.at[indice, 'bonus'] = fila['amount'] * porcentaje
  # Unir elementos de las columnas nombre y apellido separado por un espacio
  df_datos.at[indice, 'name_last_name'] = ' '.join(fila[['name', 'last_name']])
  df_datos.at[indice, 'birth_country'] = ' '.join(fila[['birth_year_mod', 'country']])

<div align= 'justify' >

### **itertuples()**

Este método itera sobre las filas del DataFrame generando tuplas. Dado esto, es un método de iteración más eficiente que el método `iterrows()`

<div/>

In [ ]:
# Aplicar itertuples a DataFrame
for row in df_datos.itertuples():
  print(row)
  print(type(row))

Pandas(Index=0, name='David', last_name='Perez', birth_year=2000, country='Chile', amount=200000.0, bonus=20000.0, name_last_name='David Perez', birth_year_mod='2000', birth_country='2000 Chile')
<class 'pandas.core.frame.Pandas'>
Pandas(Index=1, name='Oscar', last_name='Parra', birth_year=2001, country='Brasil', amount=210000.0, bonus=21000.0, name_last_name='Oscar Parra', birth_year_mod='2001', birth_country='2001 Brasil')
<class 'pandas.core.frame.Pandas'>
Pandas(Index=2, name='Elena', last_name='Berrios', birth_year=1982, country='Argentina', amount=190000.0, bonus=19000.0, name_last_name='Elena Berrios', birth_year_mod='1982', birth_country='1982 Argentina')
<class 'pandas.core.frame.Pandas'>
Pandas(Index=3, name='Diana', last_name='Diaz', birth_year=2003, country='Chile', amount=201000.0, bonus=20100.0, name_last_name='Diana Diaz', birth_year_mod='2003', birth_country='2003 Chile')
<class 'pandas.core.frame.Pandas'>
Pandas(Index=4, name='Hernan', last_name='Alvarado', birth_year=1998, country='Chile', amount=150000.0, bonus=15000.0, name_last_name='Hernan Alvarado', birth_year_mod='1998', birth_country='1998 Chile')
<class 'pandas.core.frame.Pandas'>
Pandas(Index=5, name='Maria', last_name='Leal', birth_year=1999, country='Brasil', amount=198203.0, bonus=19820.300000000003, name_last_name='Maria Leal', birth_year_mod='1999', birth_country='1999 Brasil')
<class 'pandas.core.frame.Pandas'>
Pandas(Index=6, name='David', last_name='Cornejo', birth_year=2001, country='Uruguay', amount=nan, bonus=nan, name_last_name='David Cornejo', birth_year_mod='2001', birth_country='2001 Uruguay')
<class 'pandas.core.frame.Pandas'>

<div align= 'justify' >

A continuación, aplicaremos `itertuples()` para crear una nueva columna.
<div/>

In [ ]:
for row in df_datos.itertuples():
  # Indice del DataFrame y Nombre nueva columna a crear
  df_datos.at[row.Index, 'Nombre_Completo'] = '-'.join([row.name, row.last_name])

In [ ]:
df_datos

,name,last_name,birth_year,country,amount,bonus,name_last_name,Nombre_Completo
0,David,Perez,2000,Chile,200000.0,20000.0,David Perez,David-Perez
1,Oscar,Parra,2001,Brasil,210000.0,21000.0,Oscar Parra,Oscar-Parra
2,Elena,Berrios,1982,Argentina,190000.0,19000.0,Elena Berrios,Elena-Berrios
3,Diana,Diaz,2003,Chile,201000.0,20100.0,Diana Diaz,Diana-Diaz
4,Hernan,Alvarado,1998,Chile,150000.0,15000.0,Hernan Alvarado,Hernan-Alvarado
5,Maria,Leal,1999,Brasil,198203.0,19820.3,Maria Leal,Maria-Leal
6,David,Cornejo,2001,Uruguay,NaN,NaN,David Cornejo,David-Cornejo

<div align= 'justify' >

### **apply()**

El método `apply()` se utiliza para aplicar una función a lo largo de un eje de un DataFrame o una Serie. Puede aplicarse a columnas (axis=0) o filas (axis=1).
La función se aplica a una Serie a lo largo del eje especificado.

Realziaremos un ejemplo utilizando la función `apply()`

<div/>

```python
frame[lista]

frame[[elemento, de, la, lista]]
```

In [ ]:
df_datos[['amount','bonus']]

     amount    bonus
0  200000.0  20000.0
1  210000.0  21000.0
2  190000.0  19000.0
3  201000.0  20100.0
4  150000.0  15000.0
5  198203.0  19820.3
6       NaN      NaN

In [ ]:
# Importar biblioteca
import numpy as np

# Calcular estadisticas descriptivas columnas Monto y Bono
df_datos[['amount','bonus']].apply([np.min, np.max ,np.mean, np.median, np.std])

               amount         bonus
min     150000.000000  15000.000000
max     210000.000000  21000.000000
mean    191533.833333  19153.383333
median            NaN           NaN
std      19468.664313   1946.866431

In [ ]:
df_datos[['amount','bonus']].describe().T

,count,mean,std,min,25%,50%,75%,max
amount,6.0,191533.833333,21326.853218,150000.0,192050.750,199101.50,200750.0,210000.0
bonus,6.0,19153.383333,2132.685322,15000.0,19205.075,19910.15,20075.0,21000.0

<div align= 'justify' >

### **map()**

El método `map()` se utiliza para aplicar una función a cada elemento individual del DataFrame. Dado que se aplica elemento a elemento de manera independiente no se especifica un eje.

El resultado es un objeto DataFrame.

<div/>

In [ ]:
import pandas as pd
df_datos = pd.DataFrame({'nombre':['David','Oscar','Elena','Diana','Hernan','Maria','David'],
            'apellido':['Perez','Parra','Berrios','Diaz','Alvarado','Leal','Cornejo'],
            'año_nacimiento':[2000,2001,1982,2003,1998,1999,2001],
            'Pais':['Chile','Brasil','Argentina','Chile','Chile','Brasil','Uruguay'],
            'Monto':[200000, 210000, 190000, 201000, 150000, 198203, None]})

In [ ]:
df_datos

   nombre  apellido  año_nacimiento       Pais     Monto
0   David     Perez            2000      Chile  200000.0
1   Oscar     Parra            2001     Brasil  210000.0
2   Elena   Berrios            1982  Argentina  190000.0
3   Diana      Diaz            2003      Chile  201000.0
4  Hernan  Alvarado            1998      Chile  150000.0
5   Maria      Leal            1999     Brasil  198203.0
6   David   Cornejo            2001    Uruguay       NaN

In [ ]:
df_datos[['nombre', 'apellido']].map(str.lower)

   nombre  apellido
0   david     perez
1   oscar     parra
2   elena   berrios
3   diana      diaz
4  hernan  alvarado
5   maria      leal
6   david   cornejo

In [ ]:
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nombre          7 non-null      object
 1   apellido        7 non-null      object
 2   año_nacimiento  7 non-null      int64
 3   Pais            7 non-null      object
 4   Monto           6 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 412.0+ bytes

In [ ]:
#@title Selccionar las columnas que contienen datos object
columnas_str = list(df_datos.select_dtypes(include = 'object').columns)
columnas_str

['nombre', 'apellido', 'Pais']

In [ ]:
df_datos.select_dtypes(exclude = 'object').columns

Index(['año_nacimiento', 'Monto'], dtype='object')

In [ ]:
#@title transformar contenido usando map(). Nota: No sobre escribe la información
df_datos.select_dtypes(include = 'object').map(str.lower)

   nombre  apellido       Pais
0   david     perez      chile
1   oscar     parra     brasil
2   elena   berrios  argentina
3   diana      diaz      chile
4  hernan  alvarado      chile
5   maria      leal     brasil
6   david   cornejo    uruguay

In [ ]:
#@title transformar contenido usando map() y asignandolo a las columnas seleccionadas
df_datos[columnas_str] = df_datos.select_dtypes(include = 'object').map(str.lower)

['nombre', 'apellido', 'Pais']

   nombre  apellido       Pais
0   David     Perez      Chile
1   Oscar     Parra     Brasil
2   Elena   Berrios  Argentina
3   Diana      Diaz      Chile
4  Hernan  Alvarado      Chile
5   Maria      Leal     Brasil
6   David   Cornejo    Uruguay

In [ ]:
columnas_str = list(df_datos.select_dtypes(include = 'object').columns)
columnas_str

['nombre', 'apellido', 'Pais']

In [ ]:
df_datos[columnas_str] = df_datos.select_dtypes(include = 'object').map(str.title)

In [ ]:
# Visualizar resultado
df_datos

   nombre  apellido  año_nacimiento       Pais     Monto
0   David     Perez            2000      Chile  200000.0
1   Oscar     Parra            2001     Brasil  210000.0
2   Elena   Berrios            1982  Argentina  190000.0
3   Diana      Diaz            2003      Chile  201000.0
4  Hernan  Alvarado            1998      Chile  150000.0
5   Maria      Leal            1999     Brasil  198203.0
6   David   Cornejo            2001    Uruguay       NaN

<div align= 'justify' >

### **zip()**

La función `zip()` recibe como argumento diferentes iterables y devuelve una secuencia de tuplas donde la i-ésima tupla contiene los el i-ésimos elementos de cada iterable suministrado como parámetro y según el orden qn que aparezcan.

Es útil cuando necesitamos iterar de manera simultanea dos objetos. A continuación un ejemplo de esto, combinado con un bucle `for`.
<div/>

In [ ]:
numeros_espera = [30, 25]
nombres = ["David", "Daniela"]


for numero, nombre in zip(numeros_espera, nombres):
  print(f'Bienvenid@ {nombre}. Tu número de espera es el {numero}')

Bienvenid@ David. Tu número de espera es el 30
Bienvenid@ Daniela. Tu número de espera es el 25

<div align="justify">

# [**1.4. Manejo de Errores**](#id1)<a name="id4"></a>

Algunas operaciones pueden ocasionar fallas en el programa o bien comportamientos inesperados. A fin de manejar estas situaciones, Python nos ofrece herramientas a fin de dar estabilidad a nuestros códigos. Una herramienta que debemos conocer es la sentencia try/except

```python
try:
   print(x)
except:
   print("An exception has occurred!")
```

<div/>

In [ ]:
try:
  print(3/0)
except:
  print("no es posible ejecutar lo solitado")

no es posible ejecutar lo solitado

In [ ]:
def fn_sum(a,b):
  try:
    a = float(input("Ingrese un número "))
    b = float(input("Ingrese un número "))
  except:
    print("debe indicar un número")
  try:
    print(f"La suma de {a} más {b} es {a+b}")
  except:
    print("NO es  posible sumar")

In [ ]:
fn_sum(1,"s")

Ingrese un número 10
Ingrese un número f
debe indicar un número
NO es  posible sumar

In [ ]:
#@title Realice una división y maneje el error usando las sentencias try/except
# Función suma
def fn_op_aritmeticas(a,b):
  '''
  Operación que suma y  divide dos numeros:
  Parametros:
    a,b: Deben ser numeros enteros o flotantes
  retun:
    Devuelve una tupla donde el primer valor corresponde a una suma y el segundo a una division
  '''
  try:
    suma = a + b
    division = a / b
  except:
   division = "No se puede dividir por cero"
  return suma, division

In [ ]:
fn_op_aritmeticas(3,2)

5

<div align="justify">

# [**1.5. Funciones**](#id1)<a name="id5"></a>

Cuando necesitamos ejecutar tareas de forma repetitivas podemos recurrir a las funciones. Una función nos ayudan a ejecutar una tarea específica, donde indicamos argumentos para diferentes parámetros que modifiquen su funcionamiento y resultado.

La sintaxis básica de una función es la siguiente

```python
def nombre_funcion(parametro_1, parametro_2):
  instruccion_1
  instruccion_2
  ...
  instruccion_n

  return valor/resultado

```

Donde:

- `def`: palabra reservada para definir una función.
- `nombre_funcion`: nombre que le damos a nuestra función.
- `parametro_1, parametro_2`: Lista de parámetros que operarán en la instrucción a ejecutar (opcional).
- `instruccion_1, ... instruccion_n`: Cuerpo de la función, donde se indican las acciones a ejecutar.
- `return`: Palabra reservada para retornar un resultado (opcional).

A continuación, realizaremos una función que realice la suma de dos parámetros.

In [ ]:
# Función suma
def fn_suma(a,b):
  '''
  Función que ejecuta la suma de dos valores
  Parámetros:
    a,b: Deben ser números

  '''
  resultado = a + b
  return resultado

In [ ]:
fn_suma

In [ ]:
# Argumentos
a = 2
b = 5

In [ ]:
# Ejecutar función
fn_suma(a,b)

7

In [ ]:
#@title crear función multiplicacion
# Función suma
def fn_multipliaccion(a,b):
  '''
  Función que ejecuta la multiplicacion de dos valores
  Parámetros:
    a,b: Deben ser números

  '''
  resultado = a * b
  return resultado

In [ ]:
# Ejecutar
fn_multipliaccion(a,b)

10

In [ ]:
#@title Cree una Función de Operaciones básicas
def fn_op_aritmeticas(a,b):
  '''
  Operación que suma y  divide dos numeros:
  Parametros:
    a,b: Deben ser numeros enteros o flotantes
  return:
    Devuelve una tupla donde el primer valor corresponde:
    - Suma
    - Resta
    - Multiplicacion
    - Division
  '''
  try:
    suma = a + b
    resta = a - b
    multiplicacion = a * b
    division = a / b
  except:
    division = "No se puede dividir por cero"
  resultado = suma , resta , multiplicacion , division

  return list(resultado)

In [ ]:
# Ejecutar función
resultado = fn_op_aritmeticas(a,b=0)
resultado

[2, 2, 0, 'No se puede dividir por cero']

In [ ]:
#@title Acceder al resultado de la multiplicación
resultado[2]

10

<div align="justify">

# [**1.6. Función lambda**](#id1)<a name="id6"></a>

En Python, usamos la palabra reservada `lambda` para declarar una función anónima, por lo que nos referimos a ellas como "funciones lambda". Una función anónima se refiere a una función declarada sin nombre que consta de una sola expresión. Aunque sintácticamente se ven diferentes, las funciones lambda se comportan de la misma manera que las funciones regulares que se declaran usando la palabra clave `def`, sin embargo, esta función no se crean mediante dicha palabra reservada.

Estas funciones las utilizamos cuando necesitamos realizar algo simple y no repetitivo.

Su sintaxis es la siguiente:

```python
lambda argumento: instruccion
```

<div/>

In [ ]:
# Función lambda
suma = lambda a,b: a + b
suma(2,4)

6

<div align="justify">

También, podemos combinar el uso de la función anómina `lambda` para dataframe, en caso que necesitemos recorrer los valores uno a uno a fin de aplicar la función respectiva.

<div/>

In [ ]:
df_datos

   nombre  apellido  año_nacimiento       Pais     Monto
0   David     Perez            2000      Chile  200000.0
1   Oscar     Parra            2001     Brasil  210000.0
2   Elena   Berrios            1982  Argentina  190000.0
3   Diana      Diaz            2003      Chile  201000.0
4  Hernan  Alvarado            1998      Chile  150000.0
5   Maria      Leal            1999     Brasil  198203.0
6   David   Cornejo            2001    Uruguay       NaN

In [ ]:
#@title Conocer el tipo de dato
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nombre          7 non-null      object
 1   apellido        7 non-null      object
 2   año_nacimiento  7 non-null      int64
 3   Pais            7 non-null      object
 4   Monto           6 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 412.0+ bytes

In [ ]:
#@title Seleccionar solo columnas formato texto (object)
df_datos.select_dtypes(include = 'object')

   nombre  apellido       Pais
0   David     Perez      Chile
1   Oscar     Parra     Brasil
2   Elena   Berrios  Argentina
3   Diana      Diaz      Chile
4  Hernan  Alvarado      Chile
5   Maria      Leal     Brasil
6   David   Cornejo    Uruguay

In [ ]:
#@title Seleccionar solo columnas formato númerico (number)
df_datos.select_dtypes(include = 'number')

   año_nacimiento     Monto
0            2000  200000.0
1            2001  210000.0
2            1982  190000.0
3            2003  201000.0
4            1998  150000.0
5            1999  198203.0
6            2001       NaN

In [ ]:
#@title Excluir columnas Monto
df_datos.drop(columns=['Monto'])

   nombre  apellido  año_nacimiento       Pais
0   David     Perez            2000      Chile
1   Oscar     Parra            2001     Brasil
2   Elena   Berrios            1982  Argentina
3   Diana      Diaz            2003      Chile
4  Hernan  Alvarado            1998      Chile
5   Maria      Leal            1999     Brasil
6   David   Cornejo            2001    Uruguay

In [ ]:
#@title Eliminar columna de manera permanente
del df_datos['Monto']

In [ ]:
df_datos

   nombre  apellido  año_nacimiento       Pais
0   David     Perez            2000      Chile
1   Oscar     Parra            2001     Brasil
2   Elena   Berrios            1982  Argentina
3   Diana      Diaz            2003      Chile
4  Hernan  Alvarado            1998      Chile
5   Maria      Leal            1999     Brasil
6   David   Cornejo            2001    Uruguay

In [ ]:
'uruguay'.title()

'Uruguay'

In [ ]:
#@title Transformar contenido a formato titulo
df_datos['nombre'].str.title()

0     David
1     Oscar
2     Elena
3     Diana
4    Hernan
5     Maria
6     David
Name: nombre, dtype: object

In [ ]:
#@title Pasar texto a mayúscula usando apply y lambda
df_datos.select_dtypes(exclude = 'number').apply(lambda col: col.str.upper())

   nombre  apellido       Pais
0   DAVID     PEREZ      CHILE
1   OSCAR     PARRA     BRASIL
2   ELENA   BERRIOS  ARGENTINA
3   DIANA      DIAZ      CHILE
4  HERNAN  ALVARADO      CHILE
5   MARIA      LEAL     BRASIL
6   DAVID   CORNEJO    URUGUAY

<div align = 'justify'>

Durante el transcurso del curso abordaremos nuevos métodos para mejorar nuestro manejo del lenguaje Python

<div/>