# 1. Matrices

In [3]:
import numpy as np
X = np.arange(1,10)
X

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
matriz1 = np.reshape(X,(3,3))
matriz1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
vector1 = np.arange(1,5)
vector2 = np.arange(5,9)
vector3 = np.arange(9,13)
matriz2 = np.column_stack([vector1,vector2,vector3])
matriz2

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [8]:
matriz3 = np.vstack([vector1,vector2, vector3])
matriz3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Operaciones con matrices

In [9]:
# Suma un numero a una matriz
print(matriz1 + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]

In [10]:
# multiplicacion un numero a una matriz
print(matriz1 * 10)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

In [11]:
# potencia a una matriz
print(matriz1 ** 3)

[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]

# De matrices a dataframe

In [12]:
AUTO_1 = [20, 20, 16, 17,17,22,17]
AUTO_2 = [15,11,18,23,8,4,19]
AUTO_3 = [14,11,3,21,22,12,11]
venta_autos = np.column_stack([AUTO_1,AUTO_2, AUTO_3 ])
venta_autos

array([[20, 15, 14],
       [20, 11, 11],
       [16, 18,  3],
       [17, 23, 21],
       [17,  8, 22],
       [22,  4, 12],
       [17, 19, 11]])

In [15]:
import pandas as pd
ventas_auto_df = pd.DataFrame(venta_autos,columns=["nissan",'chevrolet','suzuki'] )
ventas_auto_df

   nissan  chevrolet  suzuki
0      20         15      14
1      20         11      11
2      16         18       3
3      17         23      21
4      17          8      22
5      22          4      12
6      17         19      11

In [16]:
ventas_auto_df.index = ['1990','1991', '1992','1993', '1994','1995','1996']
ventas_auto_df

      nissan  chevrolet  suzuki
1990      20         15      14
1991      20         11      11
1992      16         18       3
1993      17         23      21
1994      17          8      22
1995      22          4      12
1996      17         19      11

In [18]:
# Acceder a un elemento especifico por posicion
ventas_auto_df.iloc[2,1]

np.int64(18)

In [19]:
#Acceder a un elemento especifico mediante nombre
ventas_auto_df.loc['1990', 'nissan']

np.int64(20)

In [20]:
#traer la fila 1990 y todas las columnas
ventas_auto_df.loc['1990', :]

nissan       20
chevrolet    15
suzuki       14
Name: 1990, dtype: int64

In [21]:
## años 1992 y 1993, chevrolet y suzuki
ventas_auto_df.loc[['1992','1993'],['chevrolet','suzuki']]

      chevrolet  suzuki
1992         18       3
1993         23      21

In [26]:
## calculos de estadisticos basicos
#promedio de ventas de 1990
ventas_auto_df.loc['1990',:].mean()
## mediana de ventas de 1990
ventas_auto_df.loc['1990',:].median()
## suma de ventas de 1990
ventas_auto_df.loc['1990',:].sum()
## maximo de ventas de 1990
ventas_auto_df.loc['1990',:].max()
## minimo de ventas de 1990
ventas_auto_df.loc['1990',:].min()

14

In [27]:
ventas_auto_df.describe()

          nissan  chevrolet     suzuki
count   7.000000   7.000000   7.000000
mean   18.428571  14.000000  13.428571
std     2.225395   6.683313   6.502747
min    16.000000   4.000000   3.000000
25%    17.000000   9.500000  11.000000
50%    17.000000  15.000000  12.000000
75%    20.000000  18.500000  17.500000
max    22.000000  23.000000  22.000000

# Cargar dataframes incorporados

In [28]:
from sklearn.datasets import load_iris
iris= load_iris()
data = pd.DataFrame(data=iris.data, columns=iris.feature_names)
data

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [29]:
data.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [32]:
data.head(2)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2

In [33]:
data.tail(2)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

# Filtros a este dataframes