# Sesion 2 — SQL I: consultar la base de coyuntura

**Ciencia de Datos para Economia (ICO09425)** · martes 11 de agosto de 2026

Hoy dejamos de mirar la base y empezamos a interrogarla. Al terminar vas a poder:

1. conectarte a `coyuntura.db` desde Python con **SQLAlchemy**;
2. elegir columnas con `SELECT` y filas con `WHERE`;
3. ordenar y recortar con `ORDER BY` y `LIMIT`;
4. cruzar las tres tablas con `JOIN`, y saber cuando usar `INNER` y cuando `LEFT`.

**La base de hoy.** Trabajamos sobre `coyuntura_clase_2026-07-31.db`, que trae **datos reales** del Banco Central de Chile y de FRED con corte al 31 de julio de 2026. Se entrega ya construida para que nadie dependa de tener sus credenciales tramitadas.\n\n> Ojo con la distincion: esta es la **base de clases**, para aprender SQL. La base de **su proyecto** la genera cada equipo desde las APIs con sus propias claves, y esa descarga programatica es lo que la rubrica evalua con 10 puntos.

---
## 1. Conectar con SQLAlchemy

En la sesion 1 usamos `sqlite3`, que es el modulo estandar de Python y solo habla SQLite. Desde hoy usamos **SQLAlchemy**, que es la misma capa que usa `carga_db.py` en el kit.

La razon es una sola linea:

```python
create_engine("sqlite:///data/coyuntura.db")            # hoy
create_engine("postgresql://usuario:clave@servidor/bd") # si el proyecto crece
```

Cambiar de motor es cambiar esa cadena. El resto del codigo no se toca. Con `sqlite3` habria que reescribirlo todo.

In [1]:
from pathlib import Path
from sqlalchemy import create_engine, text
import pandas as pd

# Para la clase usamos una base YA CONSTRUIDA con datos reales del Banco Central
# y de FRED, con corte fijo al 31 de julio de 2026. Asi la sesion no depende de
# que cada persona tenga ya sus credenciales tramitadas.
#
# Se prueba cada ruta en orden y se usa la primera que exista.
CANDIDATAS = [
    Path("data/coyuntura_2026-07-31.db"),
    Path("../data/coyuntura_2026-07-31.db"),                 
]

DB = next((ruta for ruta in CANDIDATAS if ruta.exists()), None)
if DB is None:
    raise FileNotFoundError(
        "No encuentro ninguna base de datos.\n"
        "Deja 'coyuntura_clase_2026-07-31.db' en la misma carpeta que este cuaderno, "
        "o agrega tu ruta a la lista CANDIDATAS."
    )

engine = create_engine(f"sqlite:///{DB}")
print("Base   :", DB.resolve())
print("Tamano :", round(DB.stat().st_size / 1024, 1), "KB")

Base   : C:\Users\generico_fee\Downloads\kit-inicio-coyuntura\data\coyuntura_2026-07-31.db
Tamano : 1004.0 KB

`engine` no abre una conexion todavia: es una fabrica de conexiones. Se abren y se cierran solas cuando ejecutas una consulta. Por eso no hay un `con.close()` al final de este cuaderno.

Para leer resultados usamos `pd.read_sql`, que devuelve un DataFrame de pandas.

In [2]:
def consultar(sql):
    """Ejecuta una consulta y devuelve el resultado como DataFrame."""
    # Una consulta que solo tiene comentarios o espacios no se ejecuta:
    # asi los ejercicios en blanco avisan en vez de lanzar un error cripitico.
    util = "\n".join(
        linea for linea in sql.splitlines()
        if not linea.strip().startswith("--")
    ).strip()
    if not util:
        print("La consulta esta vacia. Escribe tu SQL entre las comillas triples.")
        return None
    return pd.read_sql(sql, engine)


consultar("SELECT sqlite_version() AS version_del_motor")

  version_del_motor
0            3.51.0

---
## 2. `SELECT`: elegir columnas

Empecemos por mirar el catalogo completo.

In [3]:
consultar("SELECT * FROM series")

,id_serie,nombre,fuente,frecuencia,unidad,id_tema
0,F073.TCO.PRE.Z.D,Tipo de cambio observado (CLP/USD),BCCH,D,CLP/USD,5
1,F022.TPM.TIN.D001.NO.Z.D,Tasa de Política Monetaria (TPM),BCCH,D,% anual,4
2,F074.IPC.VAR.Z.Z.C.M,"IPC, variación mensual",BCCH,M,var. % mensual,2
3,F032.IMC.IND.Z.Z.EP18.Z.Z.0.M,Imacec (índice),BCCH,M,índice 2018=100,1
4,CPIAUCSL,IPC Estados Unidos (índice),FRED,M,índice,6
5,FEDFUNDS,Tasa Fed Funds (EE.UU.),FRED,M,% anual,6

`SELECT *` sirve para explorar, no para trabajar. En una consulta definitiva se nombran las columnas: si manana alguien agrega una columna a la tabla, el asterisco la arrastra y rompe el codigo que consume el resultado.

In [ ]:
consultar("""
SELECT nombre, fuente, frecuencia, unidad
FROM   series
""")

                               nombre fuente frecuencia           unidad
0  Tipo de cambio observado (CLP/USD)   BCCH          D          CLP/USD
1    Tasa de Política Monetaria (TPM)   BCCH          D          % anual
2              IPC, variación mensual   BCCH          M   var. % mensual
3                     Imacec (índice)   BCCH          M  índice 2018=100
4         IPC Estados Unidos (índice)   FRED          M           índice
5             Tasa Fed Funds (EE.UU.)   FRED          M          % anual

### Alias de columna con `AS`

El alias cambia el nombre en la **salida**, no en la tabla. Sirve para que el DataFrame llegue con nombres legibles.

In [48]:
consultar("""
SELECT nombre     AS indicador,
       fuente     AS origen,
       frecuencia AS periodicidad
FROM   series
""")

                            indicador origen periodicidad
0  Tipo de cambio observado (CLP/USD)   BCCH            D
1    Tasa de Política Monetaria (TPM)   BCCH            D
2              IPC, variación mensual   BCCH            M
3                     Imacec (índice)   BCCH            M
4         IPC Estados Unidos (índice)   FRED            M
5             Tasa Fed Funds (EE.UU.)   FRED            M

### `DISTINCT`: valores unicos

Pregunta economica: ¿de que fuentes se alimenta nuestro monitor?

In [8]:
consultar("SELECT DISTINCT fuente FROM series")

  fuente
0   BCCH
1   FRED

---
## 3. `WHERE`: elegir filas

`WHERE` descarta filas antes de que lleguen a Python. Esa es la diferencia entre traer 9.051 filas para quedarse con 30, y traer 30.

In [9]:
# Solo las series mensuales
consultar("""
SELECT nombre, frecuencia, unidad
FROM   series
WHERE  frecuencia = 'M'
""")

                        nombre frecuencia           unidad
0       IPC, variación mensual          M   var. % mensual
1              Imacec (índice)          M  índice 2018=100
2  IPC Estados Unidos (índice)          M           índice
3      Tasa Fed Funds (EE.UU.)          M          % anual

In [14]:
consultar("""
SELECT  DISTINCT fuente,frecuencia
FROM   series
""")

  fuente frecuencia
0   BCCH          D
1   BCCH          M
2   FRED          M

In [ ]:
# Dos condiciones a la vez
consultar("""
SELECT nombre, fuente, frecuencia
FROM   series
WHERE  fuente = 'BCCH' 
AND frecuencia = 'D'
""")

                               nombre fuente frecuencia
0  Tipo de cambio observado (CLP/USD)   BCCH          D
1    Tasa de Política Monetaria (TPM)   BCCH          D
2              IPC, variación mensual   BCCH          M
3                     Imacec (índice)   BCCH          M
4         IPC Estados Unidos (índice)   FRED          M
5             Tasa Fed Funds (EE.UU.)   FRED          M

In [ ]:
consultar("""
-- Seleccionar las columnas con frecuencia diaria o el id_serie comience con 'F0'
SELECT *
FROM   series
WHERE frecuencia = 'D'
OR id_serie LIKE 'F0%'
""")

,id_serie,nombre,fuente,frecuencia,unidad,id_tema
0,F073.TCO.PRE.Z.D,Tipo de cambio observado (CLP/USD),BCCH,D,CLP/USD,5
1,F022.TPM.TIN.D001.NO.Z.D,Tasa de Política Monetaria (TPM),BCCH,D,% anual,4
2,F074.IPC.VAR.Z.Z.C.M,"IPC, variación mensual",BCCH,M,var. % mensual,2
3,F032.IMC.IND.Z.Z.EP18.Z.Z.0.M,Imacec (índice),BCCH,M,índice 2018=100,1
4,CPIAUCSL,IPC Estados Unidos (índice),FRED,M,índice,6
5,FEDFUNDS,Tasa Fed Funds (EE.UU.),FRED,M,% anual,6

In [29]:
consultar("""
-- Seleccionar las columnas con frecuencia diaria o el id_serie termine con 'M'
SELECT *
FROM   series
WHERE frecuencia = 'D'
OR id_serie LIKE '%M'
""")

,id_serie,nombre,fuente,frecuencia,unidad,id_tema
0,F073.TCO.PRE.Z.D,Tipo de cambio observado (CLP/USD),BCCH,D,CLP/USD,5
1,F022.TPM.TIN.D001.NO.Z.D,Tasa de Política Monetaria (TPM),BCCH,D,% anual,4
2,F074.IPC.VAR.Z.Z.C.M,"IPC, variación mensual",BCCH,M,var. % mensual,2
3,F032.IMC.IND.Z.Z.EP18.Z.Z.0.M,Imacec (índice),BCCH,M,índice 2018=100,1

In [31]:
consultar("""
-- Seleccionar las columnas con frecuencia diaria o que el nombre contenga el termino 'var'
SELECT *
FROM   series
WHERE frecuencia = 'D'
OR nombre LIKE '%var%'
""")

,id_serie,nombre,fuente,frecuencia,unidad,id_tema
0,F073.TCO.PRE.Z.D,Tipo de cambio observado (CLP/USD),BCCH,D,CLP/USD,5
1,F022.TPM.TIN.D001.NO.Z.D,Tasa de Política Monetaria (TPM),BCCH,D,% anual,4
2,F074.IPC.VAR.Z.Z.C.M,"IPC, variación mensual",BCCH,M,var. % mensual,2

### El repertorio de operadores

| Operador | Para que sirve | Ejemplo |
|---|---|---|
| `=` `<>` `<` `>` `<=` `>=` | Comparar | `WHERE valor > 900` |
| `AND` `OR` `NOT` | Combinar condiciones | `WHERE fuente = 'FRED' OR frecuencia = 'D'` |
| `IN (...)` | Pertenece al conjunto | `WHERE id_tema IN (1, 2)` |
| `BETWEEN a AND b` | Rango cerrado | `WHERE fecha BETWEEN '2026-01-01' AND '2026-06-30'` |
| `LIKE` | Contiene texto (`%` es comodin) | `WHERE nombre LIKE '%IPC%'` |
| `IS NULL` / `IS NOT NULL` | Dato faltante | `WHERE valor IS NULL` |

Tres reglas que evitan la mayoria de los errores:

- El texto va entre **comillas simples**; los numeros, sin comillas.
- Las fechas en SQLite son texto con formato `'AAAA-MM-DD'`. Por eso se ordenan y comparan correctamente como si fueran fechas.
- `NULL` no se compara con `=`. Siempre `IS NULL` o `IS NOT NULL`.

In [32]:
# Buscar por texto: todas las series de precios
consultar("""
SELECT nombre, unidad
FROM   series
WHERE  nombre LIKE '%IPC%'
""")

                        nombre          unidad
0       IPC, variación mensual  var. % mensual
1  IPC Estados Unidos (índice)          índice

In [35]:
# Rango de fechas: el tipo de cambio del primer semestre de 2026
consultar("""
SELECT id_serie, fecha, valor
FROM   observaciones
WHERE  id_serie = 'F073.TCO.PRE.Z.D'
  AND  fecha BETWEEN '2026-01-01' AND '2026-06-30'
""")

             id_serie       fecha   valor
0    F073.TCO.PRE.Z.D  2026-01-02  907.13
1    F073.TCO.PRE.Z.D  2026-01-05  901.55
2    F073.TCO.PRE.Z.D  2026-01-06  905.14
3    F073.TCO.PRE.Z.D  2026-01-07  896.82
4    F073.TCO.PRE.Z.D  2026-01-08  895.33
..                ...         ...     ...
119  F073.TCO.PRE.Z.D  2026-06-23  905.78
120  F073.TCO.PRE.Z.D  2026-06-24  915.58
121  F073.TCO.PRE.Z.D  2026-06-25  921.42
122  F073.TCO.PRE.Z.D  2026-06-26  916.97
123  F073.TCO.PRE.Z.D  2026-06-30  922.34

[124 rows x 3 columns]

In [41]:
consultar("""
-- Filtrar las series F073.TCO.PRE.Z.D y FEDFUNDS entre 01-01-2026 al 05-01-2026
SELECT id_serie, fecha, valor
FROM   observaciones
WHERE (id_serie = 'F073.TCO.PRE.Z.D' 
AND fecha BETWEEN '2020-01-01' AND '2020-01-05')
OR (id_serie = 'FEDFUNDS'
AND fecha BETWEEN '2026-01-01' AND '2026-01-05')
""")

           id_serie       fecha   valor
0  F073.TCO.PRE.Z.D  2020-01-02  748.74
1  F073.TCO.PRE.Z.D  2020-01-03  754.16
2          FEDFUNDS  2026-01-01    3.64

In [42]:
consultar("""
-- Filtrar las series F073.TCO.PRE.Z.D y FEDFUNDS entre 01-01-2026 al 05-01-2026
SELECT id_serie, fecha, valor
FROM   observaciones
WHERE (id_serie = 'F073.TCO.PRE.Z.D'
OR id_serie = 'FEDFUNDS')
AND fecha BETWEEN '2026-01-01' AND '2026-01-05'
""")

           id_serie       fecha   valor
0  F073.TCO.PRE.Z.D  2026-01-02  907.13
1  F073.TCO.PRE.Z.D  2026-01-05  901.55
2          FEDFUNDS  2026-01-01    3.64

In [46]:
consultar("""
-- Filtrar las series F073.TCO.PRE.Z.D y FEDFUNDS entre 01-01-2026 al 05-01-2026
SELECT id_serie, fecha, valor
FROM   observaciones
WHERE id_serie IN('F073.TCO.PRE.Z.D','FEDFUNDS')
AND fecha BETWEEN '2026-01-01' AND '2026-01-05'
""")

           id_serie       fecha   valor
0  F073.TCO.PRE.Z.D  2026-01-02  907.13
1  F073.TCO.PRE.Z.D  2026-01-05  901.55
2          FEDFUNDS  2026-01-01    3.64

---
## 4. `ORDER BY` y `LIMIT`

**Sin `ORDER BY` el orden de las filas no esta garantizado.** Puede parecer cronologico hoy y dejar de serlo cuando la tabla crezca. Si el orden importa, hay que pedirlo.

In [43]:
# ¿Como viene el dato reciente?
consultar("""
SELECT   fecha, valor
FROM     observaciones
WHERE    id_serie = 'F073.TCO.PRE.Z.D'
ORDER BY fecha DESC
LIMIT    10
""")

        fecha   valor
0  2026-07-31  924.78
1  2026-07-30  935.57
2  2026-07-29  936.16
3  2026-07-28  941.93
4  2026-07-27  946.14
5  2026-07-24  946.24
6  2026-07-23  936.39
7  2026-07-22  932.84
8  2026-07-21  933.00
9  2026-07-20  933.92

In [45]:
# ¿Cuales fueron los maximos historicos?
consultar("""
SELECT   fecha, valor
FROM     observaciones
WHERE    id_serie = 'F073.TCO.PRE.Z.D'
ORDER BY valor DESC
LIMIT    1
""")

        fecha    valor
0  2022-07-15  1042.97

In [49]:
# ¿Cuales fueron los maximos historicos?
consultar("""
SELECT   MAX(valor) AS Maximo,
         MIN(valor) AS Minimo,
         AVG(valor) AS Promedio
FROM     observaciones
WHERE    id_serie = 'F073.TCO.PRE.Z.D'
""")

    Maximo  Minimo    Promedio
0  1042.97  455.91  696.485992

Esos dos patrones, `ORDER BY fecha DESC LIMIT 10` y `ORDER BY valor DESC LIMIT 5`, responden las dos preguntas que un area de estudios hace todos los dias: como viene el dato reciente, y cuando fue el extremo.

### Un detalle que muerde al cambiar de motor

Escribimos `SELECT` primero, pero la base lo ejecuta cuarto:

```
FROM  ->  JOIN  ->  WHERE  ->  SELECT  ->  ORDER BY  ->  LIMIT
```

Como `WHERE` corre **antes** que `SELECT`, un alias definido en `SELECT` todavia no existe cuando `WHERE` se evalua. El SQL estandar prohibe usarlo ahi.

SQLite, en cambio, lo acepta como extension propia. La celda siguiente funciona **en SQLite** y falla en PostgreSQL con `column "valor_pesos" does not exist`.

La consulta busca los dias en que el dolar cerro **sobre los 1.000 pesos**, que en la serie real son unos pocos, todos concentrados en episodios de tension.

In [51]:
# Funciona en SQLite, pero NO es SQL estandar.
consultar("""
SELECT   fecha, valor AS valor_pesos
FROM     observaciones
WHERE    id_serie = 'F073.TCO.PRE.Z.D'
  AND    valor_pesos > 1000
ORDER BY valor_pesos DESC
LIMIT    3
""")

        fecha  valor_pesos
0  2022-07-15      1042.97
1  2025-01-14      1012.76
2  2025-01-20      1012.36

In [57]:
# La forma portable: repetir la expresion en WHERE.
consultar("""
SELECT   fecha, valor AS valor_pesos
FROM     observaciones
WHERE    id_serie = 'F073.TCO.PRE.Z.D'
  AND    valor > 1000
ORDER BY valor_pesos DESC
LIMIT    3
""")

        fecha  valor_pesos
0  2022-07-15      1042.97
1  2025-01-14      1012.76
2  2025-01-20      1012.36

Las dos devuelven lo mismo hoy. Escriban siempre la segunda: el enunciado permite migrar a PostgreSQL, y ese dia la primera deja de compilar.

---
## 5. `JOIN`: cruzar las tablas

La tabla `observaciones` guarda `id_serie`, no el nombre. Guardar `'Tipo de cambio observado (CLP/USD)'` en cada una de sus 4.129 filas seria repetir el mismo texto 4.129 veces.

En vez de eso se guarda el codigo y se recupera el nombre cuando hace falta. Eso es lo que significa que la base sea **relacional**.

In [58]:
# Sin JOIN: el dato existe, pero no se entiende
consultar("SELECT id_serie, fecha, valor FROM observaciones ORDER BY fecha DESC LIMIT 5")

                   id_serie       fecha   valor
0  F022.TPM.TIN.D001.NO.Z.D  2026-07-31    4.50
1          F073.TCO.PRE.Z.D  2026-07-31  924.78
2  F022.TPM.TIN.D001.NO.Z.D  2026-07-30    4.50
3          F073.TCO.PRE.Z.D  2026-07-30  935.57
4  F022.TPM.TIN.D001.NO.Z.D  2026-07-29    4.50

In [59]:
# Con JOIN: el mismo dato, legible
consultar("""
SELECT   s.nombre, o.fecha, o.valor, s.unidad
FROM         observaciones AS o
INNER JOIN   series        AS s  ON s.id_serie = o.id_serie
ORDER BY o.fecha DESC
LIMIT    5
""")

                               nombre       fecha   valor   unidad
0    Tasa de Política Monetaria (TPM)  2026-07-31    4.50  % anual
1  Tipo de cambio observado (CLP/USD)  2026-07-31  924.78  CLP/USD
2    Tasa de Política Monetaria (TPM)  2026-07-30    4.50  % anual
3  Tipo de cambio observado (CLP/USD)  2026-07-30  935.57  CLP/USD
4    Tasa de Política Monetaria (TPM)  2026-07-29    4.50  % anual

Tres cosas de la sintaxis:

- `AS o` y `AS s` son **alias de tabla**. Acortan el resto de la consulta.
- `ON` declara **por donde se pegan** las tablas: casi siempre llave foranea contra llave primaria.
- Con alias, `o.fecha` y `s.nombre` dejan claro de donde sale cada columna. Con dos tablas parece innecesario; con tres, deja de serlo.

### `INNER` contra `LEFT`

- `INNER JOIN` conserva solo las filas que **encuentran pareja** en la otra tabla.
- `LEFT JOIN` conserva **todas** las filas de la tabla izquierda, tengan pareja o no. Donde no hay, rellena con `NULL`.

Comparalos sobre la misma pregunta: ¿que temas tiene el monitor y cuantas series hay en cada uno?

In [60]:
# INNER: solo los temas que tienen series
consultar("""
SELECT      t.tema, s.nombre
FROM        temas  AS t
INNER JOIN  series AS s ON s.id_tema = t.id_tema
ORDER BY    t.tema
""")

                 tema                              nombre
0           Actividad                     Imacec (índice)
1       Internacional         IPC Estados Unidos (índice)
2       Internacional             Tasa Fed Funds (EE.UU.)
3  Política monetaria    Tasa de Política Monetaria (TPM)
4             Precios              IPC, variación mensual
5      Sector externo  Tipo de cambio observado (CLP/USD)

In [52]:
# LEFT: todos los temas, tengan series o no
consultar("""
SELECT      t.tema, s.nombre
FROM        temas  AS t
LEFT JOIN   series AS s ON s.id_tema = t.id_tema
ORDER BY    t.tema
""")

                 tema                              nombre
0           Actividad                     Imacec (índice)
1       Internacional         IPC Estados Unidos (índice)
2       Internacional             Tasa Fed Funds (EE.UU.)
3     Mercado laboral                                None
4  Política monetaria    Tasa de Política Monetaria (TPM)
5             Precios              IPC, variación mensual
6      Sector externo  Tipo de cambio observado (CLP/USD)

In [ ]:
# LEFT actuando como un INNER
consultar("""
SELECT      t.tema, s.nombre
FROM        temas  AS t
LEFT JOIN   series AS s ON s.id_tema = t.id_tema
WHERE nombre IS NOT NULL
ORDER BY    t.tema
""")

                 tema                              nombre
0           Actividad                     Imacec (índice)
1       Internacional         IPC Estados Unidos (índice)
2       Internacional             Tasa Fed Funds (EE.UU.)
3  Política monetaria    Tasa de Política Monetaria (TPM)
4             Precios              IPC, variación mensual
5      Sector externo  Tipo de cambio observado (CLP/USD)

In [55]:
# LEFT: todos los temas, tengan series o no
consultar("""
SELECT      t.tema, s.nombre
FROM        temas  AS t
JOIN   series AS s ON s.id_tema = t.id_tema
ORDER BY    t.tema
""")

                 tema                              nombre
0           Actividad                     Imacec (índice)
1       Internacional         IPC Estados Unidos (índice)
2       Internacional             Tasa Fed Funds (EE.UU.)
3  Política monetaria    Tasa de Política Monetaria (TPM)
4             Precios              IPC, variación mensual
5      Sector externo  Tipo de cambio observado (CLP/USD)

In [56]:
# LEFT usando IS NULL
consultar("""
SELECT      t.tema, s.nombre
FROM        temas  AS t
LEFT JOIN   series AS s ON s.id_tema = t.id_tema
WHERE nombre IS  NULL
ORDER BY    t.tema
""")

              tema nombre
0  Mercado laboral   None

Busca **Mercado laboral**. Con `LEFT` aparece con `None` en la columna `nombre`; con `INNER` no aparece en absoluto.

> **La trampa:** `INNER JOIN` descarta filas **sin avisar**. Si el catalogo no tiene series de empleo, con `INNER` el tema desaparece y nadie nota el hueco.
>
> Regla practica: para **revisar** si falta algo, `LEFT`. Para **analizar** casos completos, `INNER`.

Y una consecuencia concreta para el proyecto: el kit trae 6 series y el enunciado exige 12 o mas. Esa consulta con `LEFT` es la que les va a mostrar que temas siguen vacios.

### Cruzar las tres tablas

Cada `JOIN` adicional agrega una linea. Pregunta economica: ¿que indicadores del sector externo tenemos, y cual es su dato mas reciente?

In [62]:
consultar("""
SELECT   t.tema, s.nombre, o.fecha, o.valor, s.unidad
FROM         observaciones AS o
JOIN         series        AS s  ON s.id_serie = o.id_serie
JOIN         temas         AS t  ON t.id_tema  = s.id_tema
WHERE    t.tema = 'Sector externo'
ORDER BY o.fecha DESC
LIMIT    5
""")

,tema,nombre,fecha,valor,unidad
0,Sector externo,Tipo de cambio observado (CLP/USD),2026-07-31,924.78,CLP/USD
1,Sector externo,Tipo de cambio observado (CLP/USD),2026-07-30,935.57,CLP/USD
2,Sector externo,Tipo de cambio observado (CLP/USD),2026-07-29,936.16,CLP/USD
3,Sector externo,Tipo de cambio observado (CLP/USD),2026-07-28,941.93,CLP/USD
4,Sector externo,Tipo de cambio observado (CLP/USD),2026-07-27,946.14,CLP/USD

`JOIN` a secas significa `INNER JOIN`. Escribir la palabra completa cuesta cinco letras y evita una ambiguedad al leer la consulta seis semanas despues.

---
## 6. Las consultas viven en el repositorio

La rubrica pide consultas **documentadas** en el repositorio, en archivos `.sql`. Una consulta que solo existe dentro de una celda de notebook no cuenta: no se puede reutilizar desde Power BI ni revisar en un pull request.

In [63]:
CONSULTA_ULTIMO_DATO = """
-- Ultimo dato disponible de cada indicador del monitor.
-- Usada en: analisis de coyuntura y panel de sintesis.
SELECT   t.tema, s.nombre, o.fecha, o.valor, s.unidad
FROM         observaciones AS o
JOIN         series        AS s  ON s.id_serie = o.id_serie
JOIN         temas         AS t  ON t.id_tema  = s.id_tema
ORDER BY o.fecha DESC
LIMIT    20
"""

# Guardarla en la carpeta sql/ del repositorio del equipo.
CARPETAS = [
    Path("../sql"),
    Path("kit-inicio-coyuntura/sql"),
    Path("../kit-inicio-coyuntura/sql"),
]
carpeta = next((c for c in CARPETAS if c.exists()), None)
if carpeta is None:
    carpeta = Path("sql")
    carpeta.mkdir(exist_ok=True)

archivo = carpeta / "03_consultas_ejemplo.sql"
archivo.write_text(CONSULTA_ULTIMO_DATO, encoding="utf-8")
print("Guardada en:", archivo.resolve())

consultar(CONSULTA_ULTIMO_DATO).head()

Guardada en: /Users/luiscuevas/Library/CloudStorage/GoogleDrive-luis.cuevas1@mail.udp.cl/.shortcut-targets-by-id/1HWmgLmZBNnR8T64aI7kQ1m30V2STo0Kz/Ciencia de Datos para la Economia 2026/kit-inicio-coyuntura/sql/03_consultas_ejemplo.sql

,tema,nombre,fecha,valor,unidad
0,Política monetaria,Tasa de Política Monetaria (TPM),2026-07-31,4.50,% anual
1,Sector externo,Tipo de cambio observado (CLP/USD),2026-07-31,924.78,CLP/USD
2,Política monetaria,Tasa de Política Monetaria (TPM),2026-07-30,4.50,% anual
3,Sector externo,Tipo de cambio observado (CLP/USD),2026-07-30,935.57,CLP/USD
4,Política monetaria,Tasa de Política Monetaria (TPM),2026-07-29,4.50,% anual

Ese archivo si entra al repositorio. Haganle `git add`, `git commit` y `git push` al terminar la clase: es evidencia de contribucion, que la rubrica evalua con 10 puntos.

---
## 7. Ejercicios

Escribe la consulta en la celda vacia. Las soluciones estan al final, pero intentalo primero: el **Control 1 del jueves 20 de agosto** evalua exactamente esto y no trae soluciones al final.

1. Lista el nombre y la unidad de todas las series que vienen de **FRED**.
2. Muestra las **15 observaciones mas recientes** de la TPM (`F022.TPM.TIN.D001.NO.Z.D`), con fecha y valor.
3. ¿Que series son **diarias**? Devuelve nombre y fuente, ordenado por nombre.
4. Muestra las **5 fechas en que el tipo de cambio fue mas bajo**, con su valor.
5. Usando `JOIN`, muestra el tema, el nombre y el valor de las **10 observaciones mas recientes** de indicadores de **Politica monetaria**.
6. ¿Hay algun tema **sin ninguna serie** asociada? Escribe la consulta que lo demuestre.

In [64]:
# Ejercicio 1
consultar("""
-- Escribe aqui tu consulta
""")

La consulta esta vacia. Escribe tu SQL entre las comillas triples.

In [65]:
# Ejercicio 2
consultar("""
-- Escribe aqui tu consulta
""")

La consulta esta vacia. Escribe tu SQL entre las comillas triples.

In [66]:
# Ejercicio 3
consultar("""
-- Escribe aqui tu consulta
""")

La consulta esta vacia. Escribe tu SQL entre las comillas triples.

In [67]:
# Ejercicio 4
consultar("""
-- Escribe aqui tu consulta
""")

La consulta esta vacia. Escribe tu SQL entre las comillas triples.

In [68]:
# Ejercicio 5
consultar("""
-- Escribe aqui tu consulta
""")

La consulta esta vacia. Escribe tu SQL entre las comillas triples.

In [69]:
# Ejercicio 6
consultar("""
-- Escribe aqui tu consulta
""")

La consulta esta vacia. Escribe tu SQL entre las comillas triples.

---
## 8. Soluciones

Compara tu consulta con esta. Si llegaste al mismo resultado por otro camino, tambien esta bien: en SQL casi siempre hay mas de una forma.

In [70]:
# 1. Series que vienen de FRED
consultar("""
SELECT   nombre, unidad
FROM     series
WHERE    fuente = 'FRED'
ORDER BY nombre
""")

                        nombre   unidad
0  IPC Estados Unidos (índice)   índice
1      Tasa Fed Funds (EE.UU.)  % anual

In [71]:
# 2. Las 15 observaciones mas recientes de la TPM
consultar("""
SELECT   fecha, valor
FROM     observaciones
WHERE    id_serie = 'F022.TPM.TIN.D001.NO.Z.D'
ORDER BY fecha DESC
LIMIT    15
""")

         fecha  valor
0   2026-07-31    4.5
1   2026-07-30    4.5
2   2026-07-29    4.5
3   2026-07-28    4.5
4   2026-07-27    4.5
5   2026-07-24    4.5
6   2026-07-23    4.5
7   2026-07-22    4.5
8   2026-07-21    4.5
9   2026-07-20    4.5
10  2026-07-17    4.5
11  2026-07-15    4.5
12  2026-07-14    4.5
13  2026-07-13    4.5
14  2026-07-10    4.5

In [72]:
# 3. Series diarias
consultar("""
SELECT   nombre, fuente
FROM     series
WHERE    frecuencia = 'D'
ORDER BY nombre
""")

                               nombre fuente
0    Tasa de Política Monetaria (TPM)   BCCH
1  Tipo de cambio observado (CLP/USD)   BCCH

In [73]:
# 4. Las 5 fechas de tipo de cambio mas bajo
consultar("""
SELECT   fecha, valor
FROM     observaciones
WHERE    id_serie = 'F073.TCO.PRE.Z.D'
ORDER BY valor ASC
LIMIT    5
""")

        fecha   valor
0  2011-07-29  455.91
1  2011-07-28  457.12
2  2011-08-01  457.41
3  2011-08-03  458.05
4  2011-08-02  458.51

In [74]:
# 5. Las 10 observaciones mas recientes de politica monetaria
consultar("""
SELECT   t.tema, s.nombre, o.fecha, o.valor
FROM         observaciones AS o
INNER JOIN   series        AS s  ON s.id_serie = o.id_serie
INNER JOIN   temas         AS t  ON t.id_tema  = s.id_tema
WHERE    t.tema = 'Politica monetaria'
ORDER BY o.fecha DESC
LIMIT    10
""")

Empty DataFrame
Columns: [tema, nombre, fecha, valor]
Index: []

> Si el ejercicio 5 te devolvio una tabla vacia, revisa la tilde: el tema esta guardado como `'Política monetaria'`. En SQL el texto se compara caracter por caracter, y `'Politica'` no es `'Política'`.
>
> Es un error que van a cometer con nombres de series reales del Banco Central. Cuando dudes, usa `LIKE '%monetaria%'` para no depender de la tilde.

In [75]:
# 5 bis. La version que no depende de la tilde
consultar("""
SELECT   t.tema, s.nombre, o.fecha, o.valor
FROM         observaciones AS o
INNER JOIN   series        AS s  ON s.id_serie = o.id_serie
INNER JOIN   temas         AS t  ON t.id_tema  = s.id_tema
WHERE    t.tema LIKE '%monetaria%'
ORDER BY o.fecha DESC
LIMIT    10
""")

                 tema                            nombre       fecha  valor
0  Política monetaria  Tasa de Política Monetaria (TPM)  2026-07-31    4.5
1  Política monetaria  Tasa de Política Monetaria (TPM)  2026-07-30    4.5
2  Política monetaria  Tasa de Política Monetaria (TPM)  2026-07-29    4.5
3  Política monetaria  Tasa de Política Monetaria (TPM)  2026-07-28    4.5
4  Política monetaria  Tasa de Política Monetaria (TPM)  2026-07-27    4.5
5  Política monetaria  Tasa de Política Monetaria (TPM)  2026-07-24    4.5
6  Política monetaria  Tasa de Política Monetaria (TPM)  2026-07-23    4.5
7  Política monetaria  Tasa de Política Monetaria (TPM)  2026-07-22    4.5
8  Política monetaria  Tasa de Política Monetaria (TPM)  2026-07-21    4.5
9  Política monetaria  Tasa de Política Monetaria (TPM)  2026-07-20    4.5

In [76]:
# 6. Temas sin ninguna serie asociada
consultar("""
SELECT      t.tema, s.id_serie
FROM        temas  AS t
LEFT JOIN   series AS s ON s.id_tema = t.id_tema
WHERE       s.id_serie IS NULL
""")

              tema id_serie
0  Mercado laboral     None

El ejercicio 6 combina las dos ideas centrales de la sesion: `LEFT JOIN` conserva la fila sin pareja, y `WHERE ... IS NULL` se queda justamente con esas. Es el patron estandar para responder "¿que hay de un lado que no tiene contraparte del otro?".

In [77]:
engine.dispose()
del engine
print("Conexión cerrada.")

Conexión cerrada.

---
## 9. Cierre

### Lo que queda pendiente

Hoy respondimos preguntas sobre **filas individuales**. Quedan las preguntas sobre **conjuntos de filas**:

- ¿Cual fue el promedio del dolar en cada mes?
- ¿Cuantas observaciones tiene cada serie?
- ¿Cuanto vario el IPC respecto del mismo mes del ano pasado?

El **jueves 13** vemos `GROUP BY` y funciones agregadas para las dos primeras, y funciones de ventana con `LAG` para la tercera, que es la que de verdad necesita el monitor de coyuntura.

### Para el jueves 13

1. Terminar los seis ejercicios.
2. Dejar `sql/03_consultas_equipo.sql` en el repositorio, commiteado y subido.
3. Empezar a buscar los **codigos de sus series** en <https://si3.bcentral.cl/siete>. El catalogo de 12 series es parte del Hito 1, que vence el viernes 4 de septiembre.

> El **Control 1** es el jueves 20 de agosto, en los ultimos 30 minutos de la sesion, y cubre exactamente lo de hoy y lo del jueves 13.